### ISSUE TITLE
API link is off

### ISSUE THREAD

**Issue by joaothallis** [pagarme/business-calendar#14]

**Comment by macabeus** [comment]
@joaothallis Antes de tudo, desculpa pela demora em respondê-lo 😅

Testei o link aqui da API, e está funcionando...  Por exemplo, esse link está ok: https://pagarme.github.io/business-calendar/data/brazil/2018.json

Qual você tentou usar que não deu certo?
[Tal como você pode ver aqui](https://github.com/pagarme/business-calendar/tree/master/data/brazil), temos os arquivos json a partir do ano de 2015.

**Comment by joaothallis** [comment]
@macabeus eu tentei acessar esse link: https://pagarme.github.io/business-calendar/ mas ele está ok. Obrigado pela resposta!

**Comment by macabeus** [comment]
@joaothallis Ah sim, de fato esse link está incorreto. Não havia visto ele. Obrigado por alertar!
